### ISSUE TITLE
貌似不能用了

### ISSUE THREAD

**Issue by tokki** [timothyqiu/xiami-downloader#11]
打算继续更新这个项目吗

**Comment by timothyqiu** [comment]
我试着下载了几个，没有问题。请问你下载的是哪些歌 / 专辑 / 精选集？

**Comment by tokki** [comment]
下载专辑啊 帮忙看下 我不太懂那个逻辑

**Comment by timothyqiu** [comment]
是哪个专辑？

**Comment by tokki** [comment]
446349 你试下

**Comment by timothyqiu** [comment]
我可以正常下载。请问你的完整的命令是怎样的，以及出错时的提示信息是什么？

**Comment by tokki** [comment]
啊 不会吧 我在装一下试试 删掉了

**Comment by tokki** [comment]
![image](https://cloud.githubusercontent.com/assets/237240/6797656/86dea64c-d23f-11e4-9132-e50ea07fb664.png)

**Comment by timothyqiu** [comment]
我明白了。应该是你的系统里没有 wget，抱歉错误提示没有做好。

你可以装 wget 或者加个参数选择使用内置下载工具：`python xiami.py -a 446349 -t urllib2`。

过两天会改掉，谢谢 :)

**Comment by tokki** [comment]
啊 换了新电脑 没有wget了 解决了谢谢你啦 也没有个提示时wget的问题－，－
