### ISSUE TITLE
歌曲名的问题

### ISSUE THREAD

**Issue by FanZhitao** [timothyqiu/xiami-downloader#16]
当前版本下载歌曲的默认格式（曲号 - 歌曲名 - 歌手名）中，歌曲名解析好像存在问题，使用了json中title字段。我下载的一些歌曲，这个字段的值跟专辑名是一样的。这样下载整张专辑的话，从文件名上只有曲号不一样。重现例子：`python -m xiami_downloader.cli -a 373986`

**Comment by timothyqiu** [comment]
感谢，应该是虾米最近加了 `songName` 这个字段，把原来的 `title` 含义改了 :)
