### ISSUE TITLE
can't download

### ISSUE THREAD

**Issue by arnauldb** [timothyqiu/xiami-downloader#18]
Hello,

Thank you for this tool.

I instaled it and tested it with the following album: http://www.xiami.com/album/511682
It works ok.

But when I want to download this album http://www.xiami.com/album/b1CzLyz412 It doesn't work.
I did: 

> python -m xiami_downloader.cli -a b1CzLyz412ff

But nothing. Is it because of the letters (b C z...)  in "b1CzLyz412" ?

**Comment by timothyqiu** [comment]
Hi, thank you for you bug reporting. I have not been using xiami.com for quite a while, so I didn't notice the change in the website.

It seems that xiami.com adopted a new URL naming scheme. URLs now will default to a non-canonical version without the integer ID.

I just made some modifications to support this. Hope it helps :)

**Comment by arnauldb** [comment]
谢谢! It is working now.
